### PR TITLE
Add support for lirc_odroid blaster, SPI flash and petitboot

### PR DESCRIPTION
**Pull request by mad-ady**

### CODE REVIEW

**Comment by mad-ady** [comment]
Currently fails to build with
```
drivers/built-in.o: In function `iep_iommu_info_create':
odroid-sysfs.c:(.text+0x532d8): undefined reference to `iep_iommu_ion_set_ops'
odroid-sysfs.c:(.text+0x532d8): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `iep_iommu_ion_set_ops'
```

Will try without my patches to see if it's something I activated.

**Comment by Owersun** [comment]
you need a clean build. iep_iommu_ion_set_ops was changed in implementation, but for some reason the odroid-sysfs driver never get's rebuild, the binary stays and it references wrong function

**Comment by mad-ady** [comment]
Should make clean be enough? I'll give it a try.

**Comment by mad-ady** [comment]
After make mrproper and make clean I still end up with the same failure:

drivers/built-in.o: In function `iep_iommu_info_create':
odroid-sysfs.c:(.text+0x532d8): undefined reference to
`iep_iommu_ion_set_ops'
odroid-sysfs.c:(.text+0x532d8): relocation truncated to fit:
R_AARCH64_CALL26 against undefined symbol `iep_iommu_ion_set_ops'
Makefile:1034: recipe for target 'vmlinux' failed
make: *** [vmlinux] Error 1

I've re-cloned your original branch and ran the same make (without my
patches) and I don't get the same issue, so it must be something I've
enabled... Weird...

**Comment by mad-ady** [comment]
I've retested the build with your odroidn1-4.4.y-with-le-patches and the
defconfig and I run into the same problem:
```
git clone -b odroidn1-4.4.y-with-le-patches
https://github.com/Owersun/linux-hardkernel/
cd linux-hardkernel/
make odroidn1_defconfig
make -j 6 Image dtbs modules
...
drivers/built-in.o: In function `iep_iommu_info_create':
odroid-sysfs.c:(.text+0x532a0): undefined reference to
`iep_iommu_ion_set_ops'
odroid-sysfs.c:(.text+0x532a0): relocation truncated to fit:
R_AARCH64_CALL26 against undefined symbol `iep_iommu_ion_set_ops'
Makefile:1034: recipe for target 'vmlinux' failed
make: *** [vmlinux] Error 1

```

I will try to build your other branch as well.

**Comment by Owersun** [comment]
As I've outlined few times, the function iep_iommu_ion_set_ops was reworked and it require few things to be build properly, - a clean build, and thorough flags from Makefiles. Tampering with flags, disabling Werr and stuff could make it fail like this.
Check which flags you set as default for your build environment as well. And gcc version. I use one of the very latest, the default of Ubuntu 18.10

**Comment by mad-ady** [comment]
In my last test I just cloned your repo and tried to build it without any
changes - that's why I reported it to you. Could the problem be from the
build environment? I'm using gcc-7.3.0 from ubuntu 18.04.

**Comment by Owersun** [comment]
very unlikely, except only if there are additional build flags set for your system in env varibales

**Comment by Owersun** [comment]
anyway, you really can disable the freaking odroid-sysfs driver, as it was written for kernel version that is a year old and is the only driver there from Odroid and really affects nothing I guess.

**Comment by mad-ady** [comment]
The kernel compiled and runs fine, but it seems gpio numbers are no longer
the same as with HK's 4.4.114 (e.g. there is no gpio 1033). I tried the IR
blaster with gpio 33 instead and seems to be working. No idea why
Hardkernel chose to offset their GPIOs.

I'll also test petitboot functionality and report back tomorrow.

Cheers!
